networks:
  tproxy-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}

services:
  xray-tproxy:
    container_name: xray-tproxy
    build: .
    environment:
      - CONTAINER_IP=${CONTAINER_IP}
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.route_localnet=1
    volumes:
      - ./vless.conf:/app/vless.conf:ro
    networks:
      tproxy-net:
        ipv4_address: ${CONTAINER_IP}
    restart: unless-stopped
